spring:
  security:
      oauth2:
        client:
          registration:
            google:
              client-id: 226461791927-567ql5hveeifsjkko8qdve3o60ijes14.apps.googleusercontent.com
              client-secret: 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
